server:
  port: 9000

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.syes.syes_springboot.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://hasdsd.cn:3307/syes?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  mvc:
    static-path-pattern: /file/** # 静态资源访问
  resources:
    static-locations: file:${my.file-config.uploadPath} # 静态资源目录


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

my:
  server: localhost # 上传到服务器需要改这个
  file-config:
    uploadPath: 'D:/下载/不用思考，删这个文件夹/' # 文件下载到哪里，记得屁股加个杠
    downloadPath: '${my.server}:${server.port}/file/' # 存url到数据库时用的他