server:
    port: 8000


spring:
    datasource:
        url: jdbc:mysql://hasdsd.cn:3307/syes?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
    servlet:
        multipart:
            max-file-size: 10GB
            max-request-size: 10GB
    mvc:
        static-path-pattern: /file/** # 静态资源访问
    resources:
        static-locations: file:${my.file-config.uploadPath} # 静态资源目录

mybatis:
    mapper-locations: mapper/*.xml
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: false

my:
    server: # 上传到服务器需要改这个
        name: localhost
        uploadPath: 'D:/下载/不用思考，删这个文件夹/' # 文件下载到哪里，记得屁股加个杠

    file-config:
        uploadPath: '${my.server.uploadPath}'
        downloadPath: '${my.server.name}:${server.port}/file/' # 存url到数据库时用的他
